
import { Course, Instructor, Student, StudentGroup, Enrollment, Testimonial, FAQ, Category, NewsletterSubscription, Ad } from './types';

export const PARTNERS = [
  { name: 'Aramco', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Saudi_Aramco_logo.svg/320px-Saudi_Aramco_logo.svg.png' },
  { name: 'NEOM', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/NEOM_logo.svg/320px-NEOM_logo.svg.png' },
  { name: 'Etisalat', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Etisalat_logo.svg/320px-Etisalat_logo.svg.png' },
  { name: 'CIB', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Commercial_International_Bank_Egypt_Logo.svg/320px-Commercial_International_Bank_Egypt_Logo.svg.png' },
];

export const INSTRUCTORS: Instructor[] = [
  {
    id: 'inst1',
    name: 'Dr. Ahmed Mansour',
    role: 'Lead Strategist',
    experience: '15+ Years Executive Experience',
    qualifications: ['PhD in Strategic Management', 'Former McKinsey Consultant', 'Member of Egypt Economic Council'],
    bio: 'Dr. Mansour specializes in digital transformation of traditional industries across Egypt and North Africa.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974',
    specialization: 'Digital Strategy',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4'
  },
  {
    id: 'inst2',
    name: 'Sarah Al-Qahtani',
    role: 'Sovereign Fund Analyst',
    experience: '12 Years Wealth Management',
    qualifications: ['CFA Charterholder', 'MSc Finance (LSE)', 'Ex-Advisor to Saudi Investment Authority'],
    bio: 'Sarah provides deep analytical insights into GCC financial markets and sovereign wealth fund allocation strategies.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1976',
    specialization: 'High Finance',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4'
  },
  {
    id: 'inst3',
    name: 'Eng. Omar Zayed',
    role: 'Chief Technology Officer',
    experience: '20+ Years Systems Architecture',
    qualifications: ['Stanford AI Research Fellow', 'Patented AI Solutions Specialist', 'Regional Tech Innovator Award'],
    bio: 'Omar is a pioneer in implementing machine learning models specifically designed for the linguistic and cultural context of the Arab world.',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070',
    specialization: 'Artificial Intelligence',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4'
  },
  {
    id: 'inst4',
    name: 'Abdalla Yasin',
    role: 'Data Analytics Instructor',
    experience: '10+ Years Data Analytics & BI',
    qualifications: ['Ph.D. Candidate in Computer Science (Fayoum University)', 'M.Sc. in Data Science', 'Power BI Instructor for DEBI & DEPI national programs'],
    bio: 'Abdalla Yasin is a seasoned freelance Data Analyst with over 10 years of experience delivering actionable insights to 70+ international clients. He serves as an Assistant Lecturer at Nahda University and is a prominent Power BI Instructor for national programs including the Digital Egypt Builders Initiative (DEBI) and the Digital Egypt Pioneers Initiative (DEPI). His expertise spans business intelligence, KPI dashboard development, data visualization, and machine learning.',
    image: '/images/abdalla-yasin.jpg',
    specialization: 'Data Analytics & Business Intelligence'
  }
];

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Executive Digital Transformation Strategy',
    category: 'Strategy',
    instructor: 'Dr. Ahmed Mansour',
    price: 8500,
    currency: 'EGP',
    rating: 4.9,
    enrolled: 1240,
    capacity: 200,
    duration: '12 Weeks',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070',
    level: 'Advanced',
    description: 'A comprehensive roadmap for leaders to transition traditional business models into the digital age, focusing on regional MENA opportunities.',
    prerequisites: ['Bachelor\'s Degree', '3+ years of management experience', 'Basic understanding of digital tools'],
    modules: [
      { id: 'm1_1', title: 'Foundations of Digital Business' },
      { id: 'm1_2', title: 'Agile Leadership in MENA' },
      { id: 'm1_3', title: 'Cloud Integration & Legacy Systems' },
      { id: 'm1_4', title: 'Data-Driven Decision Making' }
    ]
  },
  {
    id: '2',
    title: 'Financial Analysis for GCC Sovereign Funds',
    category: 'Finance',
    instructor: 'Sarah Al-Qahtani',
    price: 2200,
    currency: 'SAR',
    rating: 4.8,
    enrolled: 850,
    capacity: 150,
    duration: '8 Weeks',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015',
    level: 'Advanced',
    description: 'Master the complex world of institutional investment and sovereign wealth management within the Gulf Cooperation Council framework.',
    prerequisites: ['Finance or Accounting degree', 'Proficiency in Excel', 'CFA level 1 candidate preferred'],
    modules: [
      { id: 'm2_1', title: 'SWF Legal Frameworks' },
      { id: 'm2_2', title: 'Portfolio Diversification Strategies' },
      { id: 'm2_3', title: 'Risk Assessment & Mitigation' }
    ]
  },
  {
    id: '3',
    title: 'AI Architecture & Machine Learning',
    category: 'Technology',
    instructor: 'Eng. Omar Zayed',
    price: 2500,
    currency: 'AED',
    rating: 4.9,
    enrolled: 2100,
    capacity: 300,
    duration: '24 Weeks',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070',
    level: 'Intermediate',
    description: 'Deep dive into neural networks and LLMs with a specific focus on Arabic Natural Language Processing and localized datasets.',
    prerequisites: ['Python proficiency', 'Basic statistics knowledge', 'Fundamental linear algebra'],
    modules: [
      { id: 'm3_1', title: 'Python for AI Fundamentals' },
      { id: 'm3_2', title: 'Neural Networks Architecture' },
      { id: 'm3_3', title: 'Arabic NLP & LLM Fine-tuning' },
      { id: 'm3_4', title: 'Ethical AI Deployment' }
    ]
  },
  {
    id: '4',
    title: 'Smart City Real Estate Investment',
    category: 'Investment',
    instructor: 'Mahmoud El-Sayed',
    price: 5200,
    currency: 'EGP',
    rating: 4.7,
    enrolled: 560,
    capacity: 100,
    duration: '6 Weeks',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070',
    level: 'Intermediate',
    description: 'Analyze real estate trends in emerging MENA smart cities like NEOM and New Cairo Administrative Capital.',
    prerequisites: ['Basic real estate knowledge', 'Interest in urban planning', 'Analytical mindset'],
    modules: [
      { id: 'm4_1', title: 'Urban Planning 2.0' },
      { id: 'm4_2', title: 'PropTech Innovations' },
      { id: 'm4_3', title: 'MENA Real Estate Regulations' }
    ]
  }
];

export const CATEGORIES_LIST = ['All', 'Strategy', 'Finance', 'Technology', 'Investment', 'Management'];

// ─── Seed: Student Groups ───────────────────────────────────────────────────

const now = Date.now();
const day = 86400000;

export const SEED_GROUPS: StudentGroup[] = [
  {
    id: 'grp_seed_1',
    name: { en: 'Batch 2026-A — Strategy', ar: 'دفعة 2026-أ — استراتيجية' },
    description: { en: 'Spring 2026 cohort for Strategy track', ar: 'دفعة ربيع 2026 لمسار الاستراتيجية' },
    color: '#2563eb',
    instructorId: 'inst1',
    courseId: '1',
    capacity: 30,
    schedule: 'Sun/Tue 6-8 PM',
    startDate: now - 30 * day,
    endDate: now + 60 * day,
    isActive: true,
    studentCount: 5,
    createdAt: now - 60 * day,
    updatedAt: now,
  },
  {
    id: 'grp_seed_2',
    name: { en: 'Batch 2026-B — Finance', ar: 'دفعة 2026-ب — مالية' },
    description: { en: 'Spring 2026 cohort for Finance track', ar: 'دفعة ربيع 2026 لمسار المالية' },
    color: '#7c3aed',
    instructorId: 'inst2',
    courseId: '2',
    capacity: 25,
    schedule: 'Mon/Wed 7-9 PM',
    startDate: now - 15 * day,
    endDate: now + 75 * day,
    isActive: true,
    studentCount: 3,
    createdAt: now - 45 * day,
    updatedAt: now,
  },
  {
    id: 'grp_seed_3',
    name: { en: 'AI Intensive — Q1', ar: 'مكثف الذكاء الاصطناعي — ر1' },
    description: { en: 'Intensive AI & ML program Q1 2026', ar: 'برنامج الذكاء الاصطناعي المكثف الربع الأول 2026' },
    color: '#0d9488',
    instructorId: 'inst3',
    courseId: '3',
    capacity: 40,
    schedule: 'Sat 10 AM-2 PM',
    startDate: now - 10 * day,
    endDate: now + 150 * day,
    isActive: true,
    studentCount: 4,
    createdAt: now - 30 * day,
    updatedAt: now,
  },
];

// ─── Seed: Students ─────────────────────────────────────────────────────────

export const SEED_STUDENTS: Student[] = [
  {
    id: 'stu_seed_1',
    name: 'Youssef Khaled',
    email: 'youssef.k@example.com',
    phone: '+201012345678',
    country: 'EG',
    gender: 'male',
    dateOfBirth: '1998-03-15',
    nationalId: '29803151234567',
    level: 'intermediate',
    lifecycleStage: 'active',
    groupIds: ['grp_seed_1'],
    assignedInstructorId: 'inst1',
    enrolledCourseIds: ['1'],
    isActive: true,
    source: 'website',
    tags: ['scholarship', 'dean-list'],
    notes: 'High-performing student, potential TA candidate.',
    createdAt: now - 50 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: 'stu_seed_2',
    name: 'Nour Al-Din',
    email: 'nour.aldin@example.com',
    phone: '+966501234567',
    country: 'SA',
    gender: 'male',
    level: 'advanced',
    lifecycleStage: 'enrolled',
    groupIds: ['grp_seed_2'],
    assignedInstructorId: 'inst2',
    enrolledCourseIds: ['2'],
    isActive: true,
    source: 'referral',
    tags: ['corporate-sponsor'],
    createdAt: now - 40 * day,
    updatedAt: now - 5 * day,
  },
  {
    id: 'stu_seed_3',
    name: 'Fatima Hassan',
    email: 'fatima.h@example.com',
    phone: '+971501234567',
    country: 'AE',
    gender: 'female',
    dateOfBirth: '2000-07-22',
    level: 'beginner',
    lifecycleStage: 'active',
    groupIds: ['grp_seed_3'],
    assignedInstructorId: 'inst3',
    enrolledCourseIds: ['3'],
    isActive: true,
    source: 'social',
    parentName: 'Hassan Al-Maktoum',
    parentPhone: '+971509876543',
    createdAt: now - 35 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'stu_seed_4',
    name: 'Omar Mostafa',
    email: 'omar.m@example.com',
    phone: '+201098765432',
    country: 'EG',
    gender: 'male',
    level: 'intermediate',
    lifecycleStage: 'prospect',
    groupIds: [],
    enrolledCourseIds: [],
    isActive: true,
    source: 'ad',
    notes: 'Interested in AI track, follow up next week.',
    createdAt: now - 10 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: 'stu_seed_5',
    name: 'Layla Ibrahim',
    email: 'layla.ibrahim@example.com',
    phone: '+96512345678',
    country: 'KW',
    gender: 'female',
    dateOfBirth: '1995-11-08',
    level: 'advanced',
    lifecycleStage: 'alumni',
    groupIds: ['grp_seed_1'],
    assignedInstructorId: 'inst1',
    enrolledCourseIds: ['1', '4'],
    isActive: true,
    source: 'referral',
    tags: ['alumni-ambassador'],
    address: 'Kuwait City, Kuwait',
    createdAt: now - 120 * day,
    updatedAt: now - 20 * day,
  },
  {
    id: 'stu_seed_6',
    name: 'Khalid Bin Rashid',
    email: 'khalid.r@example.com',
    phone: '+97444123456',
    country: 'QA',
    gender: 'male',
    level: 'beginner',
    lifecycleStage: 'lead',
    groupIds: [],
    enrolledCourseIds: [],
    isActive: true,
    source: 'website',
    createdAt: now - 5 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: 'stu_seed_7',
    name: 'Amira Sayed',
    email: 'amira.s@example.com',
    phone: '+201155678901',
    country: 'EG',
    gender: 'female',
    dateOfBirth: '1999-01-30',
    level: 'intermediate',
    lifecycleStage: 'active',
    groupIds: ['grp_seed_1', 'grp_seed_3'],
    assignedInstructorId: 'inst3',
    enrolledCourseIds: ['1', '3'],
    isActive: true,
    source: 'walk_in',
    tags: ['full-time'],
    createdAt: now - 25 * day,
    updatedAt: now,
  },
  {
    id: 'stu_seed_8',
    name: 'Mohammed Al-Farsi',
    email: 'mohammed.f@example.com',
    phone: '+96891234567',
    country: 'OM',
    gender: 'male',
    level: 'advanced',
    lifecycleStage: 'enrolled',
    groupIds: ['grp_seed_2'],
    assignedInstructorId: 'inst2',
    enrolledCourseIds: ['2'],
    isActive: true,
    source: 'social',
    createdAt: now - 20 * day,
    updatedAt: now - 4 * day,
  },
  {
    id: 'stu_seed_9',
    name: 'Rania Abdel-Nasser',
    email: 'rania.a@example.com',
    phone: '+201234567890',
    country: 'EG',
    gender: 'female',
    level: 'intermediate',
    lifecycleStage: 'inactive',
    groupIds: ['grp_seed_3'],
    enrolledCourseIds: ['3'],
    isActive: false,
    source: 'website',
    notes: 'Paused due to travel. Will resume next quarter.',
    createdAt: now - 90 * day,
    updatedAt: now - 30 * day,
  },
  {
    id: 'stu_seed_10',
    name: 'Sultan Al-Dosari',
    email: 'sultan.d@example.com',
    phone: '+966551234567',
    country: 'SA',
    gender: 'male',
    dateOfBirth: '1997-06-12',
    level: 'beginner',
    lifecycleStage: 'enrolled',
    groupIds: ['grp_seed_2'],
    assignedInstructorId: 'inst2',
    enrolledCourseIds: ['2', '4'],
    isActive: true,
    source: 'ad',
    tags: ['scholarship'],
    createdAt: now - 15 * day,
    updatedAt: now - 2 * day,
  },
];

// ─── Seed: Enrollments ──────────────────────────────────────────────────────

export const SEED_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enroll_seed_1',
    studentId: 'stu_seed_1',
    studentName: 'Youssef Khaled',
    studentEmail: 'youssef.k@example.com',
    studentPhone: '+201012345678',
    courseId: '1',
    courseTitle: 'Executive Digital Transformation Strategy',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentAmount: 8500,
    paymentCurrency: 'EGP',
    enrolledAt: now - 45 * day,
    paymentDate: now - 44 * day,
    invoiceNumber: 'INV-2026-001',
  },
  {
    id: 'enroll_seed_2',
    studentId: 'stu_seed_2',
    studentName: 'Nour Al-Din',
    studentEmail: 'nour.aldin@example.com',
    studentPhone: '+966501234567',
    courseId: '2',
    courseTitle: 'Financial Analysis for GCC Sovereign Funds',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'credit_card',
    paymentAmount: 2200,
    paymentCurrency: 'SAR',
    enrolledAt: now - 38 * day,
    paymentDate: now - 38 * day,
    invoiceNumber: 'INV-2026-002',
  },
  {
    id: 'enroll_seed_3',
    studentId: 'stu_seed_3',
    studentName: 'Fatima Hassan',
    studentEmail: 'fatima.h@example.com',
    studentPhone: '+971501234567',
    courseId: '3',
    courseTitle: 'AI Architecture & Machine Learning',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'credit_card',
    paymentAmount: 2500,
    paymentCurrency: 'AED',
    enrolledAt: now - 30 * day,
    paymentDate: now - 29 * day,
    invoiceNumber: 'INV-2026-003',
  },
  {
    id: 'enroll_seed_4',
    studentId: 'stu_seed_5',
    studentName: 'Layla Ibrahim',
    studentEmail: 'layla.ibrahim@example.com',
    courseId: '1',
    courseTitle: 'Executive Digital Transformation Strategy',
    status: 'completed',
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentAmount: 8500,
    paymentCurrency: 'EGP',
    enrolledAt: now - 110 * day,
    completedAt: now - 30 * day,
    paymentDate: now - 108 * day,
    invoiceNumber: 'INV-2025-042',
  },
  {
    id: 'enroll_seed_5',
    studentId: 'stu_seed_5',
    studentName: 'Layla Ibrahim',
    studentEmail: 'layla.ibrahim@example.com',
    courseId: '4',
    courseTitle: 'Smart City Real Estate Investment',
    status: 'completed',
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    paymentAmount: 5200,
    paymentCurrency: 'EGP',
    enrolledAt: now - 100 * day,
    completedAt: now - 25 * day,
    paymentDate: now - 99 * day,
    invoiceNumber: 'INV-2025-043',
  },
  {
    id: 'enroll_seed_6',
    studentId: 'stu_seed_7',
    studentName: 'Amira Sayed',
    studentEmail: 'amira.s@example.com',
    courseId: '3',
    courseTitle: 'AI Architecture & Machine Learning',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'credit_card',
    paymentAmount: 2500,
    paymentCurrency: 'AED',
    enrolledAt: now - 20 * day,
    paymentDate: now - 20 * day,
    invoiceNumber: 'INV-2026-006',
  },
  {
    id: 'enroll_seed_7',
    studentId: 'stu_seed_8',
    studentName: 'Mohammed Al-Farsi',
    studentEmail: 'mohammed.f@example.com',
    courseId: '2',
    courseTitle: 'Financial Analysis for GCC Sovereign Funds',
    status: 'pending',
    paymentStatus: 'pending',
    paymentAmount: 2200,
    paymentCurrency: 'SAR',
    enrolledAt: now - 18 * day,
    invoiceNumber: 'INV-2026-007',
  },
  {
    id: 'enroll_seed_8',
    studentId: 'stu_seed_10',
    studentName: 'Sultan Al-Dosari',
    studentEmail: 'sultan.d@example.com',
    courseId: '2',
    courseTitle: 'Financial Analysis for GCC Sovereign Funds',
    status: 'confirmed',
    paymentStatus: 'paid',
    paymentMethod: 'bank_transfer',
    paymentAmount: 2200,
    paymentCurrency: 'SAR',
    enrolledAt: now - 12 * day,
    paymentDate: now - 11 * day,
    invoiceNumber: 'INV-2026-008',
  },
];

// ─── Seed: Testimonials ─────────────────────────────────────────────────────

export const SEED_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test_seed_1',
    studentName: 'Layla Ibrahim',
    studentRole: 'Strategy Alumna — Kuwait',
    content: 'Elite Academy completely transformed my career path. The digital strategy course gave me frameworks I use daily as a project lead at a top Kuwaiti firm.',
    rating: 5,
    courseId: '1',
    visible: true,
    order: 1,
    createdAt: now - 30 * day,
    updatedAt: now - 30 * day,
  },
  {
    id: 'test_seed_2',
    studentName: 'Nour Al-Din',
    studentRole: 'Finance Professional — Saudi Arabia',
    content: 'The sovereign funds course was incredibly practical. Sarah Al-Qahtani\'s real-world insights into GCC markets were invaluable.',
    rating: 5,
    courseId: '2',
    visible: true,
    order: 2,
    createdAt: now - 25 * day,
    updatedAt: now - 25 * day,
  },
  {
    id: 'test_seed_3',
    studentName: 'Fatima Hassan',
    studentRole: 'AI Enthusiast — UAE',
    content: 'The AI & ML program is world-class. The focus on Arabic NLP sets it apart from any other program in the region.',
    rating: 4,
    courseId: '3',
    visible: true,
    order: 3,
    createdAt: now - 20 * day,
    updatedAt: now - 20 * day,
  },
];

// ─── Seed: FAQs ─────────────────────────────────────────────────────────────

export const SEED_FAQS: FAQ[] = [
  {
    id: 'faq_seed_1',
    question: { en: 'What are the admission requirements?', ar: 'ما هي متطلبات القبول؟' },
    answer: { en: 'Most programs require a bachelor\'s degree and relevant work experience. Some advanced courses may have additional prerequisites listed on the course page.', ar: 'تتطلب معظم البرامج درجة البكالوريوس وخبرة عمل ذات صلة. قد تحتوي بعض الدورات المتقدمة على متطلبات إضافية مدرجة في صفحة الدورة.' },
    category: 'Admissions',
    order: 1,
    visible: true,
    createdAt: now - 60 * day,
    updatedAt: now - 60 * day,
  },
  {
    id: 'faq_seed_2',
    question: { en: 'Are courses available in Arabic?', ar: 'هل الدورات متاحة باللغة العربية؟' },
    answer: { en: 'Yes! All our courses offer bilingual support. Lectures, materials, and assessments are available in both Arabic and English.', ar: 'نعم! جميع دوراتنا تقدم دعمًا ثنائي اللغة. المحاضرات والمواد والتقييمات متاحة باللغتين العربية والإنجليزية.' },
    category: 'Programs',
    order: 2,
    visible: true,
    createdAt: now - 55 * day,
    updatedAt: now - 55 * day,
  },
  {
    id: 'faq_seed_3',
    question: { en: 'What payment methods do you accept?', ar: 'ما هي طرق الدفع المقبولة؟' },
    answer: { en: 'We accept bank transfers, credit cards (Visa/MasterCard), and cash payments at our offices. Installment plans are also available for select programs.', ar: 'نقبل التحويلات البنكية وبطاقات الائتمان (فيزا/ماستركارد) والدفع النقدي في مكاتبنا. كما تتوفر خطط التقسيط لبرامج مختارة.' },
    category: 'Payment',
    order: 3,
    visible: true,
    createdAt: now - 50 * day,
    updatedAt: now - 50 * day,
  },
  {
    id: 'faq_seed_4',
    question: { en: 'Do you offer certificates upon completion?', ar: 'هل تقدمون شهادات عند الإتمام؟' },
    answer: { en: 'Yes, all graduates receive a verified digital certificate recognized by MENA regulatory bodies. Certificates can be shared on LinkedIn and other platforms.', ar: 'نعم، يحصل جميع الخريجين على شهادة رقمية موثقة معترف بها من الجهات التنظيمية في المنطقة. يمكن مشاركة الشهادات على لينكد إن ومنصات أخرى.' },
    category: 'Programs',
    order: 4,
    visible: true,
    createdAt: now - 45 * day,
    updatedAt: now - 45 * day,
  },
  {
    id: 'faq_seed_5',
    question: { en: 'Can I attend classes remotely?', ar: 'هل يمكنني حضور الدروس عن بُعد؟' },
    answer: { en: 'Selected programs offer a hybrid model with both in-person and online attendance options. Check individual course pages for availability.', ar: 'تقدم برامج مختارة نموذجًا هجينًا مع خيارات الحضور الشخصي والمباشر عبر الإنترنت. تحقق من صفحات الدورات الفردية للتوفر.' },
    category: 'Programs',
    order: 5,
    visible: true,
    createdAt: now - 40 * day,
    updatedAt: now - 40 * day,
  },
];

// ─── Seed: Categories ───────────────────────────────────────────────────────

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_seed_1',
    name: { en: 'Strategy', ar: 'استراتيجية' },
    slug: 'strategy',
    description: { en: 'Strategic management and leadership programs', ar: 'برامج الإدارة الاستراتيجية والقيادة' },
    color: '#2563eb',
    order: 1,
    visible: true,
    courseCount: 1,
    createdAt: now - 90 * day,
    updatedAt: now,
  },
  {
    id: 'cat_seed_2',
    name: { en: 'Finance', ar: 'مالية' },
    slug: 'finance',
    description: { en: 'Financial analysis, investment, and wealth management', ar: 'التحليل المالي والاستثمار وإدارة الثروات' },
    color: '#7c3aed',
    order: 2,
    visible: true,
    courseCount: 1,
    createdAt: now - 90 * day,
    updatedAt: now,
  },
  {
    id: 'cat_seed_3',
    name: { en: 'Technology', ar: 'تكنولوجيا' },
    slug: 'technology',
    description: { en: 'AI, machine learning, and digital technologies', ar: 'الذكاء الاصطناعي والتعلم الآلي والتقنيات الرقمية' },
    color: '#0d9488',
    order: 3,
    visible: true,
    courseCount: 1,
    createdAt: now - 90 * day,
    updatedAt: now,
  },
  {
    id: 'cat_seed_4',
    name: { en: 'Investment', ar: 'استثمار' },
    slug: 'investment',
    description: { en: 'Real estate and capital investment programs', ar: 'برامج الاستثمار العقاري ورأس المال' },
    color: '#ea580c',
    order: 4,
    visible: true,
    courseCount: 1,
    createdAt: now - 90 * day,
    updatedAt: now,
  },
  {
    id: 'cat_seed_5',
    name: { en: 'Management', ar: 'إدارة' },
    slug: 'management',
    description: { en: 'Business management and operations', ar: 'إدارة الأعمال والعمليات' },
    color: '#16a34a',
    order: 5,
    visible: true,
    courseCount: 0,
    createdAt: now - 90 * day,
    updatedAt: now,
  },
];

// ─── Seed: Newsletter Subscribers ───────────────────────────────────────────

export const SEED_NEWSLETTERS: NewsletterSubscription[] = [
  { id: 'nl_seed_1', email: 'ahmed.khalil@example.com', subscribedAt: now - 50 * day, source: 'footer', isActive: true },
  { id: 'nl_seed_2', email: 'sara.nasser@example.com', subscribedAt: now - 40 * day, source: 'popup', isActive: true },
  { id: 'nl_seed_3', email: 'mona.ibrahim@example.com', subscribedAt: now - 30 * day, source: 'footer', isActive: true },
  { id: 'nl_seed_4', email: 'ali.hassan@example.com', subscribedAt: now - 20 * day, source: 'landing', isActive: true },
  { id: 'nl_seed_5', email: 'dina.farouk@example.com', subscribedAt: now - 10 * day, source: 'footer', isActive: false },
];

// ─── Seed: Ads ──────────────────────────────────────────────────────────────

export const SEED_ADS: Ad[] = [
  {
    id: 'ad_seed_1',
    title: { en: 'Spring Enrollment — 20% Off', ar: 'تسجيل الربيع — خصم 20%' },
    content: { en: 'Enroll in any course before March 31 and get 20% off tuition. Limited seats available!', ar: 'سجّل في أي دورة قبل 31 مارس واحصل على خصم 20% على الرسوم. المقاعد محدودة!' },
    placement: 'banner',
    status: 'active',
    startDate: now - 15 * day,
    endDate: now + 20 * day,
    targetPages: ['home', 'courses'],
    priority: 10,
    impressions: 3420,
    clicks: 187,
    visible: true,
    createdAt: now - 15 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: 'ad_seed_2',
    title: { en: 'Free AI Workshop', ar: 'ورشة ذكاء اصطناعي مجانية' },
    content: { en: 'Join our free introductory AI workshop this Saturday. Register now to reserve your spot.', ar: 'انضم لورشتنا التعريفية المجانية في الذكاء الاصطناعي هذا السبت. سجّل الآن لحجز مقعدك.' },
    placement: 'popup',
    status: 'active',
    startDate: now - 5 * day,
    endDate: now + 5 * day,
    targetPages: ['home'],
    priority: 8,
    impressions: 1200,
    clicks: 95,
    visible: true,
    createdAt: now - 5 * day,
    updatedAt: now - 1 * day,
  },
];
