import type { User, Enrollment, ContactSubmission, Testimonial, FAQ, Category } from '@/types';

const DAY = 86400000;

function daysAgo(days: number): number {
  return Date.now() - days * DAY;
}

export function seedSampleData(): void {
  const hasStudents = localStorage.getItem('elite_academy_students');
  const hasEnrollments = localStorage.getItem('elite_academy_enrollments');
  const hasContacts = localStorage.getItem('elite_academy_contacts');

  if (hasStudents || hasEnrollments || hasContacts) {
    return;
  }

  // ── Students ──────────────────────────────────────────────────────────

  const students: User[] = [
    {
      id: 'stu_001',
      email: 'ahmed.hassan@gmail.com',
      displayName: 'Ahmed Hassan',
      phone: '+201012345678',
      country: 'EG',
      role: 'student',
      createdAt: daysAgo(160),
      updatedAt: daysAgo(5),
      lastLogin: daysAgo(1),
      isActive: true,
      lifecycleStage: 'active',
      notes: 'High-performing student. Interested in advanced AI courses next quarter.',
      tags: ['vip', 'corporate'],
      source: 'website',
      preferredLanguage: 'ar',
    },
    {
      id: 'stu_002',
      email: 'fatima.rashidi@outlook.com',
      displayName: 'Fatima Al-Rashidi',
      phone: '+966501234567',
      country: 'SA',
      role: 'student',
      createdAt: daysAgo(140),
      updatedAt: daysAgo(10),
      lastLogin: daysAgo(3),
      isActive: true,
      lifecycleStage: 'active',
      tags: ['finance', 'gcc'],
      source: 'referral',
      preferredLanguage: 'ar',
    },
    {
      id: 'stu_003',
      email: 'omar.khaled@yahoo.com',
      displayName: 'Omar Khaled',
      phone: '+201155567890',
      country: 'EG',
      role: 'student',
      createdAt: daysAgo(120),
      updatedAt: daysAgo(15),
      lastLogin: daysAgo(7),
      isActive: true,
      lifecycleStage: 'alumni',
      notes: 'Completed real estate course. May be interested in leadership track.',
      tags: ['real-estate'],
      source: 'social',
      preferredLanguage: 'en',
    },
    {
      id: 'stu_004',
      email: 'sara.abdullah@gmail.com',
      displayName: 'Sara Abdullah',
      phone: '+971501234567',
      country: 'AE',
      role: 'student',
      createdAt: daysAgo(100),
      updatedAt: daysAgo(8),
      lastLogin: daysAgo(2),
      isActive: true,
      lifecycleStage: 'enrolled',
      tags: ['ai', 'tech'],
      source: 'ad',
      preferredLanguage: 'en',
    },
    {
      id: 'stu_005',
      email: 'yousef.qahtani@hotmail.com',
      displayName: 'Yousef Al-Qahtani',
      phone: '+966551234567',
      country: 'SA',
      role: 'student',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(20),
      lastLogin: daysAgo(14),
      isActive: true,
      lifecycleStage: 'alumni',
      source: 'referral',
      preferredLanguage: 'ar',
    },
    {
      id: 'stu_006',
      email: 'layla.mahmoud@gmail.com',
      displayName: 'Layla Mahmoud',
      phone: '+201223456789',
      country: 'EG',
      role: 'student',
      createdAt: daysAgo(75),
      updatedAt: daysAgo(3),
      lastLogin: daysAgo(1),
      isActive: true,
      lifecycleStage: 'active',
      notes: 'Interested in enrolling in the finance track next.',
      tags: ['eager-learner'],
      source: 'website',
      preferredLanguage: 'ar',
    },
    {
      id: 'stu_007',
      email: 'khalid.dosari@outlook.sa',
      displayName: 'Khalid Al-Dosari',
      phone: '+966541234567',
      country: 'SA',
      role: 'student',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(30),
      lastLogin: daysAgo(30),
      isActive: false,
      lifecycleStage: 'inactive',
      notes: 'Cancelled enrollment due to scheduling conflict. May return next semester.',
      source: 'social',
      preferredLanguage: 'ar',
    },
    {
      id: 'stu_008',
      email: 'noor.ibrahim@gmail.com',
      displayName: 'Noor Ibrahim',
      phone: '+96565012345',
      country: 'KW',
      role: 'student',
      createdAt: daysAgo(50),
      updatedAt: daysAgo(2),
      lastLogin: daysAgo(1),
      isActive: true,
      lifecycleStage: 'enrolled',
      tags: ['corporate', 'it'],
      source: 'ad',
      preferredLanguage: 'en',
    },
    {
      id: 'stu_009',
      email: 'mariam.alali@gmail.com',
      displayName: 'Mariam Al-Ali',
      phone: '+97455123456',
      country: 'QA',
      role: 'student',
      createdAt: daysAgo(40),
      updatedAt: daysAgo(5),
      lastLogin: daysAgo(4),
      isActive: true,
      lifecycleStage: 'prospect',
      tags: ['finance', 'gcc'],
      source: 'other',
      preferredLanguage: 'ar',
    },
    // Staff users with new roles
    {
      id: 'staff_001',
      email: 'sara.editor@eliteacademy.com',
      displayName: 'Sara El-Masry',
      phone: '+201098765432',
      country: 'EG',
      role: 'content_creator' as any,
      createdAt: daysAgo(90),
      updatedAt: daysAgo(2),
      lastLogin: daysAgo(0),
      isActive: true,
      source: 'other',
      preferredLanguage: 'en',
    },
    {
      id: 'staff_002',
      email: 'omar.mod@eliteacademy.com',
      displayName: 'Omar Khalil',
      phone: '+201155667788',
      country: 'EG',
      role: 'moderator' as any,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(1),
      lastLogin: daysAgo(0),
      isActive: true,
      source: 'other',
      preferredLanguage: 'ar',
    },
  ];

  // ── Course price map ──────────────────────────────────────────────────

  // Must match COURSES in constants.ts
  const courses = [
    { id: '1', title: 'Executive Digital Transformation Strategy', price: 8500, currency: 'EGP' },
    { id: '2', title: 'Financial Analysis for GCC Sovereign Funds', price: 2200, currency: 'SAR' },
    { id: '3', title: 'AI Architecture & Machine Learning', price: 2500, currency: 'AED' },
    { id: '4', title: 'Smart City Real Estate Investment', price: 5200, currency: 'EGP' },
  ] as const;

  // ── Enrollments ───────────────────────────────────────────────────────

  const enrollments: Enrollment[] = [
    // ~40% confirmed + paid (5-6)
    {
      id: 'enr_001',
      studentId: 'stu_001',
      studentName: 'Ahmed Hassan',
      studentEmail: 'ahmed.hassan@gmail.com',
      studentPhone: '+201012345678',
      courseId: courses[0].id,
      courseTitle: courses[0].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'bank_transfer',
      paymentAmount: courses[0].price,
      paymentCurrency: courses[0].currency,
      enrolledAt: daysAgo(150),
    },
    {
      id: 'enr_002',
      studentId: 'stu_002',
      studentName: 'Fatima Al-Rashidi',
      studentEmail: 'fatima.rashidi@outlook.com',
      studentPhone: '+966501234567',
      courseId: courses[1].id,
      courseTitle: courses[1].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'credit_card',
      paymentAmount: courses[1].price,
      paymentCurrency: courses[1].currency,
      enrolledAt: daysAgo(130),
    },
    {
      id: 'enr_003',
      studentId: 'stu_004',
      studentName: 'Sara Abdullah',
      studentEmail: 'sara.abdullah@gmail.com',
      studentPhone: '+971501234567',
      courseId: courses[2].id,
      courseTitle: courses[2].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'credit_card',
      paymentAmount: courses[2].price,
      paymentCurrency: courses[2].currency,
      enrolledAt: daysAgo(85),
    },
    {
      id: 'enr_004',
      studentId: 'stu_006',
      studentName: 'Layla Mahmoud',
      studentEmail: 'layla.mahmoud@gmail.com',
      studentPhone: '+201223456789',
      courseId: courses[3].id,
      courseTitle: courses[3].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'bank_transfer',
      paymentAmount: courses[3].price,
      paymentCurrency: courses[3].currency,
      enrolledAt: daysAgo(70),
    },
    {
      id: 'enr_005',
      studentId: 'stu_008',
      studentName: 'Noor Ibrahim',
      studentEmail: 'noor.ibrahim@gmail.com',
      studentPhone: '+96565012345',
      courseId: courses[0].id,
      courseTitle: courses[0].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'credit_card',
      paymentAmount: courses[0].price,
      paymentCurrency: courses[0].currency,
      enrolledAt: daysAgo(45),
    },
    {
      id: 'enr_006',
      studentId: 'stu_009',
      studentName: 'Mariam Al-Ali',
      studentEmail: 'mariam.alali@gmail.com',
      studentPhone: '+97455123456',
      courseId: courses[1].id,
      courseTitle: courses[1].title,
      status: 'confirmed',
      paymentStatus: 'paid',
      paymentMethod: 'cash',
      paymentAmount: courses[1].price,
      paymentCurrency: courses[1].currency,
      enrolledAt: daysAgo(35),
    },

    // ~20% completed + paid (3)
    {
      id: 'enr_007',
      studentId: 'stu_001',
      studentName: 'Ahmed Hassan',
      studentEmail: 'ahmed.hassan@gmail.com',
      studentPhone: '+201012345678',
      courseId: courses[1].id,
      courseTitle: courses[1].title,
      status: 'completed',
      paymentStatus: 'paid',
      paymentMethod: 'bank_transfer',
      paymentAmount: courses[1].price,
      paymentCurrency: courses[1].currency,
      enrolledAt: daysAgo(170),
      completedAt: daysAgo(110),
    },
    {
      id: 'enr_008',
      studentId: 'stu_003',
      studentName: 'Omar Khaled',
      studentEmail: 'omar.khaled@yahoo.com',
      studentPhone: '+201155567890',
      courseId: courses[3].id,
      courseTitle: courses[3].title,
      status: 'completed',
      paymentStatus: 'paid',
      paymentMethod: 'credit_card',
      paymentAmount: courses[3].price,
      paymentCurrency: courses[3].currency,
      enrolledAt: daysAgo(115),
      completedAt: daysAgo(50),
    },
    {
      id: 'enr_009',
      studentId: 'stu_005',
      studentName: 'Yousef Al-Qahtani',
      studentEmail: 'yousef.qahtani@hotmail.com',
      studentPhone: '+966551234567',
      courseId: courses[0].id,
      courseTitle: courses[0].title,
      status: 'completed',
      paymentStatus: 'paid',
      paymentMethod: 'bank_transfer',
      paymentAmount: courses[0].price,
      paymentCurrency: courses[0].currency,
      enrolledAt: daysAgo(88),
      completedAt: daysAgo(20),
    },

    // ~25% pending + pending (3-4)
    {
      id: 'enr_010',
      studentId: 'stu_003',
      studentName: 'Omar Khaled',
      studentEmail: 'omar.khaled@yahoo.com',
      studentPhone: '+201155567890',
      courseId: courses[2].id,
      courseTitle: courses[2].title,
      status: 'pending',
      paymentStatus: 'pending',
      paymentAmount: courses[2].price,
      paymentCurrency: courses[2].currency,
      enrolledAt: daysAgo(10),
      notes: 'Awaiting bank transfer confirmation',
    },
    {
      id: 'enr_011',
      studentId: 'stu_006',
      studentName: 'Layla Mahmoud',
      studentEmail: 'layla.mahmoud@gmail.com',
      studentPhone: '+201223456789',
      courseId: courses[1].id,
      courseTitle: courses[1].title,
      status: 'pending',
      paymentStatus: 'pending',
      paymentAmount: courses[1].price,
      paymentCurrency: courses[1].currency,
      enrolledAt: daysAgo(5),
    },
    {
      id: 'enr_012',
      studentId: 'stu_009',
      studentName: 'Mariam Al-Ali',
      studentEmail: 'mariam.alali@gmail.com',
      studentPhone: '+97455123456',
      courseId: courses[2].id,
      courseTitle: courses[2].title,
      status: 'pending',
      paymentStatus: 'pending',
      paymentAmount: courses[2].price,
      paymentCurrency: courses[2].currency,
      enrolledAt: daysAgo(3),
      notes: 'Requested installment payment plan',
    },

    // ~15% cancelled / refunded (2)
    {
      id: 'enr_013',
      studentId: 'stu_007',
      studentName: 'Khalid Al-Dosari',
      studentEmail: 'khalid.dosari@outlook.sa',
      studentPhone: '+966541234567',
      courseId: courses[0].id,
      courseTitle: courses[0].title,
      status: 'cancelled',
      paymentStatus: 'refunded',
      paymentMethod: 'credit_card',
      paymentAmount: courses[0].price,
      paymentCurrency: courses[0].currency,
      enrolledAt: daysAgo(55),
      notes: 'Student requested cancellation due to scheduling conflict',
    },
    {
      id: 'enr_014',
      studentId: 'stu_005',
      studentName: 'Yousef Al-Qahtani',
      studentEmail: 'yousef.qahtani@hotmail.com',
      studentPhone: '+966551234567',
      courseId: courses[3].id,
      courseTitle: courses[3].title,
      status: 'cancelled',
      paymentStatus: 'pending',
      paymentAmount: courses[3].price,
      paymentCurrency: courses[3].currency,
      enrolledAt: daysAgo(25),
      notes: 'Never completed payment, auto-cancelled',
    },
  ];

  // ── Contact Submissions ───────────────────────────────────────────────

  const contacts: ContactSubmission[] = [
    {
      id: 'cnt_001',
      name: 'Hala Nasser',
      email: 'hala.nasser@corporate.com',
      phone: '+966501112233',
      subject: 'partnership',
      message:
        'We are a corporate training firm based in Riyadh and would like to explore partnership opportunities with Elite Academy. We are interested in co-delivering programs to our corporate clients across the GCC region.',
      status: 'responded',
      submittedAt: daysAgo(55),
      respondedAt: daysAgo(52),
    },
    {
      id: 'cnt_002',
      name: 'Tarek Mostafa',
      email: 'tarek.m@gmail.com',
      phone: '+201098765432',
      subject: 'enrollment',
      message:
        'I am interested in enrolling in the Strategic Financial Leadership course. Could you please share details about the next cohort start date and whether there are any early-bird discounts available?',
      status: 'responded',
      submittedAt: daysAgo(42),
      respondedAt: daysAgo(40),
    },
    {
      id: 'cnt_003',
      name: 'Rania Qasim',
      email: 'rania.qasim@outlook.com',
      subject: 'general',
      message:
        'Could you tell me more about the certification that comes with completing the Executive Leadership Program? Is it accredited by any international body?',
      status: 'read',
      submittedAt: daysAgo(28),
    },
    {
      id: 'cnt_004',
      name: 'Faisal Al-Harbi',
      email: 'faisal.harbi@company.sa',
      phone: '+966559876543',
      subject: 'enrollment',
      message:
        'Our company would like to enroll five employees in the Digital Transformation & AI course. Do you offer group discounts for corporate enrollments?',
      status: 'read',
      submittedAt: daysAgo(18),
    },
    {
      id: 'cnt_005',
      name: 'Dina Farouk',
      email: 'dina.farouk@gmail.com',
      phone: '+201112233445',
      subject: 'support',
      message:
        'I completed my payment for the Investment & Portfolio Management course three days ago but have not received any confirmation email yet. Can you please check the status of my enrollment?',
      status: 'new',
      submittedAt: daysAgo(8),
    },
    {
      id: 'cnt_006',
      name: 'Ali Mansour',
      email: 'ali.mansour@hotmail.com',
      subject: 'general',
      message:
        'What are the prerequisites for the Investment & Portfolio Management course? I have a background in accounting but no direct investment experience.',
      status: 'new',
      submittedAt: daysAgo(4),
    },
    {
      id: 'cnt_007',
      name: 'Nadia Al-Suwaidi',
      email: 'nadia.suwaidi@gov.ae',
      phone: '+971521234567',
      subject: 'partnership',
      message:
        'We are a government training department in Abu Dhabi exploring options to bring executive development programs to our leadership team. Please share your partnership and customisation options.',
      status: 'new',
      submittedAt: daysAgo(2),
    },
  ];

  // ── Testimonials ─────────────────────────────────────────────────────

  const testimonials: Testimonial[] = [
    {
      id: 'test_001',
      studentName: 'Ahmed Hassan',
      studentRole: 'Software Engineer',
      content: 'The Executive Digital Transformation Strategy course completely changed how I approach technology leadership. The instructors brought real-world case studies from the MENA region that made every concept immediately applicable.',
      rating: 5,
      courseId: '1',
      visible: true,
      order: 1,
      createdAt: daysAgo(100),
      updatedAt: daysAgo(100),
    },
    {
      id: 'test_002',
      studentName: 'Fatima Al-Rashidi',
      studentRole: 'Financial Analyst',
      content: 'The Financial Analysis for GCC Sovereign Funds course gave me deep insights into regional investment strategies. The curriculum is rigorous and the networking opportunities with fellow professionals were invaluable.',
      rating: 5,
      courseId: '2',
      visible: true,
      order: 2,
      createdAt: daysAgo(90),
      updatedAt: daysAgo(90),
    },
    {
      id: 'test_003',
      studentName: 'Sara Abdullah',
      studentRole: 'AI Researcher',
      content: 'The AI Architecture & Machine Learning course exceeded my expectations. The hands-on projects and mentorship from industry experts helped me transition into a senior AI role within three months of completing the program.',
      rating: 5,
      courseId: '3',
      visible: true,
      order: 3,
      createdAt: daysAgo(70),
      updatedAt: daysAgo(70),
    },
    {
      id: 'test_004',
      studentName: 'Omar Khaled',
      studentRole: 'Real Estate Developer',
      content: 'Elite Academy\'s Smart City Real Estate Investment course provided a comprehensive understanding of modern urban development. The case studies on Dubai and NEOM were particularly insightful for my work in Egypt.',
      rating: 4,
      courseId: '4',
      visible: true,
      order: 4,
      createdAt: daysAgo(50),
      updatedAt: daysAgo(50),
    },
    {
      id: 'test_005',
      studentName: 'Noor Ibrahim',
      studentRole: 'IT Manager',
      content: 'I enrolled in the Digital Transformation course to upskill my team leadership abilities. The flexible schedule and excellent online platform made it easy to balance learning with my full-time job in Kuwait.',
      rating: 4,
      courseId: '1',
      visible: true,
      order: 5,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(40),
    },
    {
      id: 'test_006',
      studentName: 'Mariam Al-Ali',
      studentRole: 'Investment Associate',
      content: 'The quality of instruction at Elite Academy is world-class. The financial analysis course helped me secure a promotion at my firm in Doha. I highly recommend it to any finance professional in the GCC.',
      rating: 5,
      courseId: '2',
      visible: true,
      order: 6,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(30),
    },
  ];

  // ── FAQs ────────────────────────────────────────────────────────────

  const faqs: FAQ[] = [
    {
      id: 'faq_001',
      question: { en: 'How do I enroll in a course?', ar: 'كيف يمكنني التسجيل في دورة؟' },
      answer: { en: 'You can enroll by visiting our course catalog, selecting the course you are interested in, and clicking the "Enroll Now" button. You will be guided through the registration and payment process.', ar: 'يمكنك التسجيل من خلال زيارة كتالوج الدورات لدينا واختيار الدورة التي تهمك والنقر على زر "سجل الآن". سيتم إرشادك خلال عملية التسجيل والدفع.' },
      category: 'enrollment',
      order: 1,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_002',
      question: { en: 'What payment methods do you accept?', ar: 'ما هي طرق الدفع المقبولة؟' },
      answer: { en: 'We accept bank transfers, credit cards (Visa, MasterCard), and cash payments at our offices. For corporate enrollments, we also offer invoice-based payment with net-30 terms.', ar: 'نقبل التحويلات البنكية وبطاقات الائتمان (فيزا، ماستركارد) والدفع النقدي في مكاتبنا. للتسجيلات المؤسسية، نوفر أيضًا الدفع بالفواتير مع شروط صافي 30 يومًا.' },
      category: 'payment',
      order: 2,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_003',
      question: { en: 'Do you offer certificates upon course completion?', ar: 'هل تقدمون شهادات عند إكمال الدورة؟' },
      answer: { en: 'Yes, all participants who successfully complete a course receive a professional certificate from Elite Academy. Our certificates are recognized by leading organizations across Egypt and the GCC region.', ar: 'نعم، جميع المشاركين الذين يكملون الدورة بنجاح يحصلون على شهادة مهنية من أكاديمية إيليت. شهاداتنا معترف بها من قبل المؤسسات الرائدة في مصر ومنطقة الخليج.' },
      category: 'certificates',
      order: 3,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_004',
      question: { en: 'Can I get a refund if I cancel my enrollment?', ar: 'هل يمكنني استرداد المبلغ إذا ألغيت تسجيلي؟' },
      answer: { en: 'Refund requests made at least 14 days before the course start date are eligible for a full refund. Requests made 7-14 days before receive a 50% refund. No refunds are available within 7 days of the course start date.', ar: 'طلبات الاسترداد المقدمة قبل 14 يومًا على الأقل من تاريخ بدء الدورة مؤهلة لاسترداد كامل. الطلبات المقدمة قبل 7-14 يومًا تحصل على استرداد 50٪. لا تتوفر عمليات استرداد خلال 7 أيام من تاريخ بدء الدورة.' },
      category: 'payment',
      order: 4,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_005',
      question: { en: 'Are courses available online or only in-person?', ar: 'هل الدورات متاحة عبر الإنترنت أم حضوريًا فقط؟' },
      answer: { en: 'We offer both online and in-person formats. Many of our courses are available in a hybrid format, allowing you to attend sessions remotely while still participating in interactive workshops and networking events.', ar: 'نقدم كلا الصيغتين عبر الإنترنت والحضورية. العديد من دوراتنا متاحة بصيغة هجينة، مما يتيح لك حضور الجلسات عن بُعد مع المشاركة في ورش العمل التفاعلية وفعاليات التواصل.' },
      category: 'general',
      order: 5,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_006',
      question: { en: 'Do you offer corporate or group discounts?', ar: 'هل تقدمون خصومات للشركات أو المجموعات؟' },
      answer: { en: 'Yes, we offer attractive group discounts for organizations enrolling 3 or more participants. Contact our corporate training team for customized pricing and tailored programs.', ar: 'نعم، نقدم خصومات جذابة للمؤسسات التي تسجل 3 مشاركين أو أكثر. تواصل مع فريق التدريب المؤسسي لدينا للحصول على أسعار مخصصة وبرامج مصممة حسب الطلب.' },
      category: 'enrollment',
      order: 6,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_007',
      question: { en: 'What are the prerequisites for advanced courses?', ar: 'ما هي المتطلبات المسبقة للدورات المتقدمة؟' },
      answer: { en: 'Prerequisites vary by course. Generally, advanced courses require relevant professional experience or completion of our introductory-level course in the same track. Specific requirements are listed on each course page.', ar: 'تختلف المتطلبات المسبقة حسب الدورة. بشكل عام، تتطلب الدورات المتقدمة خبرة مهنية ذات صلة أو إكمال دورتنا التمهيدية في نفس المسار. المتطلبات المحددة مدرجة في صفحة كل دورة.' },
      category: 'general',
      order: 7,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'faq_008',
      question: { en: 'How can I contact support?', ar: 'كيف يمكنني التواصل مع الدعم؟' },
      answer: { en: 'You can reach our support team via the contact form on our website, by email at support@eliteacademy.com, or through WhatsApp. Our team responds within 24 business hours.', ar: 'يمكنك التواصل مع فريق الدعم لدينا عبر نموذج الاتصال على موقعنا أو عبر البريد الإلكتروني على support@eliteacademy.com أو من خلال واتساب. يرد فريقنا خلال 24 ساعة عمل.' },
      category: 'support',
      order: 8,
      visible: true,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
  ];

  // ── Categories ──────────────────────────────────────────────────────

  const categories: Category[] = [
    {
      id: 'cat_001',
      name: { en: 'Digital Transformation', ar: 'التحول الرقمي' },
      slug: 'digital-transformation',
      description: { en: 'Courses on leveraging technology for organizational change', ar: 'دورات حول الاستفادة من التكنولوجيا للتغيير المؤسسي' },
      icon: 'monitor',
      color: '#0d9488',
      order: 1,
      visible: true,
      courseCount: 1,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'cat_002',
      name: { en: 'Finance & Investment', ar: 'المالية والاستثمار' },
      slug: 'finance-investment',
      description: { en: 'Financial analysis, portfolio management, and sovereign fund strategies', ar: 'التحليل المالي وإدارة المحافظ واستراتيجيات الصناديق السيادية' },
      icon: 'trending-up',
      color: '#2563eb',
      order: 2,
      visible: true,
      courseCount: 1,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'cat_003',
      name: { en: 'Artificial Intelligence', ar: 'الذكاء الاصطناعي' },
      slug: 'artificial-intelligence',
      description: { en: 'AI architecture, machine learning, and data science programs', ar: 'برامج هندسة الذكاء الاصطناعي والتعلم الآلي وعلوم البيانات' },
      icon: 'cpu',
      color: '#7c3aed',
      order: 3,
      visible: true,
      courseCount: 1,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'cat_004',
      name: { en: 'Real Estate', ar: 'العقارات' },
      slug: 'real-estate',
      description: { en: 'Smart city development, property investment, and urban planning', ar: 'تطوير المدن الذكية والاستثمار العقاري والتخطيط الحضري' },
      icon: 'building',
      color: '#ea580c',
      order: 4,
      visible: true,
      courseCount: 1,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
    {
      id: 'cat_005',
      name: { en: 'Leadership & Management', ar: 'القيادة والإدارة' },
      slug: 'leadership-management',
      description: { en: 'Executive leadership, strategic management, and organizational development', ar: 'القيادة التنفيذية والإدارة الاستراتيجية والتطوير المؤسسي' },
      icon: 'users',
      color: '#dc2626',
      order: 5,
      visible: true,
      courseCount: 0,
      createdAt: daysAgo(200),
      updatedAt: daysAgo(200),
    },
  ];

  // ── Persist ───────────────────────────────────────────────────────────

  localStorage.setItem('elite_academy_students', JSON.stringify(students));
  localStorage.setItem('elite_academy_enrollments', JSON.stringify(enrollments));
  localStorage.setItem('elite_academy_contacts', JSON.stringify(contacts));
  localStorage.setItem('elite_academy_testimonials', JSON.stringify(testimonials));
  localStorage.setItem('elite_academy_faqs', JSON.stringify(faqs));
  localStorage.setItem('elite_academy_categories', JSON.stringify(categories));
}
